services:

  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .envd/development/database
      - .envd/development/web

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .envd/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
